build:
  maxIssues: -1
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude: [ ]
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    #    - 'XmlOutputReport'
    #   - 'HtmlOutputReport'
    - 'MdOutputReport'
    - 'SarifOutputReport'

comments:
  active: true
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false
  excludes:
    - '.*/test/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
    - '.*UI.kt'

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 20
  NestedBlockDepth:
    active: true
    threshold: 3
  LongParameterList:
    active: true
    functionThreshold: 5
    constructorThreshold: 5
    ignoreDefaultParameters: true
  LargeClass:
    active: true
    threshold: 150
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
  ComplexMethod:
    active: true
    threshold: 10
  MethodOverloading:
    active: false
    threshold: 5
  TooManyFunctions:
    active: false
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10
  ComplexCondition:
    active: true
    threshold: 3
  LabeledExpression:
    active: false
  StringLiteralDuplication:
    active: false
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: true
    dispatcherNames:
      - 'IO'
      - 'Default'
      - 'Unconfined'
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunSwallowedCancellation:
    active: false
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames:
      - 'toString'
      - 'hashCode'
      - 'equals'
      - 'finalize'
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'Exception'
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'InterruptedException'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions:
      - 'IllegalArgumentException'
      - 'IllegalStateException'
      - 'IOException'
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingNewInstanceOfSameException:
    active: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z$][a-zA-Z_$]*$'
  ForbiddenClassName:
    active: false
    forbiddenName: [ '' ]
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ignoreAnnotated: ['Composable']
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  MemberNameEqualsClassName:
    active: false
    ignoreOverridden: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '^([A-Z_]*|serialVersionUID)$'
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 30
  VariableMinLength:
    active: false
    minimumVariableNameLength: 3
  VariableNaming:
    active: true
    variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: true
  WrongEqualsTypeParameter:
    active: false
  IteratorHasNextCallsNextMethod:
    active: false
  ExplicitGarbageCollectionCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: false
  IteratorNotThrowingNoSuchElementException:
    active: false
  UnreachableCode:
    active: true
  LateinitUsage:
    active: false
    excludeAnnotatedProperties: [ '' ]
    ignoreOnClassesPattern: ''
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: false
  UselessPostfixExpression:
    active: false

style:
  active: true
  ReturnCount:
    active: true
    max: 2
  ThrowsCount:
    active: true
    max: 2
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: false
  CollapsibleIfStatements:
    active: false
  EqualsNullCall:
    active: false
  ForbiddenComment:
    active: false
    values:
      - 'TODO:'
      - 'FIXME:'
      - 'STOPSHIP:'
  ForbiddenImport:
    active: false
    imports:
      - ''
  SpacingBetweenPackageAndImports:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
    maxJumpCount: 1
  ModifierOrder:
    active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: false
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    excludes:
      - '.*/test/.*'
      - '.*Test.kt'
      - '.*Spec.kt'
      - '.*UI.kt'
  WildcardImport:
    active: false
    excludeImports:
      - 'java.util.*'
      - 'kotlinx.android.synthetic.*'
  SafeCast:
    active: true
  MaxLineLength:
    active: false
    maxLineLength: 120
    excludePackageStatements: false
    excludeImportStatements: false
  ProtectedMemberInFinalClass:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  UnnecessaryParentheses:
    active: false
  UnnecessaryInheritance:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: 'to'
  UseDataClass:
    active: false
  UnnecessaryAbstractClass:
    active: false
  OptionalUnit:
    active: false
  ExpressionBodySyntax:
    active: false
  UnusedImports:
    active: true
  NestedClassesVisibility:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  FunctionOnlyReturningConstant:
    active: false
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'
